apiVersion: v1
kind: Service
metadata:
  name: ext-authz
  namespace: ext-authz
spec:
  selector:
    app: ext-authz
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
